### ISSUE TITLE
The code is slow

### ISSUE THREAD

**Issue by yashpathack** [aniruddha0pandey/Background_Musicplayer#1]
Your code is slow! Solution is simple.

**Comment by pandevim** [comment]
@yashpathack 
I know the javascript implementation is horrific.
And god knows why I used silly **div** and not **Ordered List**.
Would you mind to debug?

**Comment by yashpathack** [comment]
Okay, let me contribute then!

**Comment by pandevim** [comment]
@yashpathack 
Appreciate ya.
Waiting for you pull request 😊.
